### ISSUE TITLE
Get JupyterHub running with XSEDE JetStream Cloud using Kubernetes

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/data-life-cycle-cloud#3]
While [JupyterHub can be installed on a single node on JetStream](#2), the real power of the Cloud is scalability, which can be provided by Kubernetes.  The suggested approach for getting JupyterHub going on the Cloud is provided in the guide ["Zero-to-JupyterHub"](http://zero-to-jupyterhub.readthedocs.io/en/latest/).     [Yuvi Panda gave a presentation](http://wiki.esipfed.org/index.php/Interoperability_and_Technology/Tech_Dive_Webinar_Series#6_June_2017:_.22Installing_JupyterHub_in_the_Cloud_using_Kubernetes_Helm.22:_Yuvi_Panda) on this installation approach which uses Helm, illustrating deployment on Google Cloud. 

It has proven harder to get this going on JetStream OpenStack, however.   We are working with JetStream support to overcome this.

**Comment by zonca** [comment]
this is very interesting! do you have any update on this?

**Comment by ntrip6** [comment]
Walkthrough from Yuvi's recent workshop
https://zero-to-jupyterhub.readthedocs.io/en/latest/index.html

Rich, your link above to installing JupyterHub on a single node on Jetstream doesn't work. Are those directions available?

**Comment by rsignell-usgs** [comment]
We now have this guide: https://zonca.github.io/2017/12/scalable-jupyterhub-kubernetes-jetstream.html
and I have verified that it works, so closing.
