### ISSUE TITLE
Create repositories for Docker configurations

### ISSUE THREAD

**Issue by isuftin** [USGS-CMG/data-life-cycle-cloud#8]
@rsignell-usgs We should create at least two new GitHub repositories

- data-life-cycle-cloud-docker-thredds
- data-life-cycle-cloud-docker-jupyterhub

I'd like to have those as individual repositories so that I may tag them individually as well as set up Travis CI testing for them 

Would you like me to create the original repos in USGS-CIDA and you fork them @ USGS-CMG or would you like for them to originate here?

**Comment by rsignell-usgs** [comment]
I'll create them here.

**Comment by rsignell-usgs** [comment]
@isuftin , done!
